# Generated by Django 5.2.5 on 2025-11-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('message', 'New Message'), ('project_update', 'Project Update'), ('event_reminder', 'Event Reminder'), ('topic_reply', 'Topic Reply'), ('mention', 'Mention'), ('like', 'Like'), ('follow', 'Follow'), ('project_join_request', 'Project Join Request'), ('project_request_approved', 'Project Request Approved'), ('project_request_rejected', 'Project Request Rejected'), ('other', 'Other')], max_length=30),
        ),
    ]
