# Generated by Django 5.2.5 on 2025-11-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('message', 'New Message'), ('project_update', 'Project Update'), ('event_reminder', 'Event Reminder'), ('topic_reply', 'Topic Reply'), ('mention', 'Mention'), ('like', 'Like'), ('follow', 'Follow'), ('other', 'Other')], max_length=20),
        ),
    ]
