# Generated by Django 5.2.5 on 2025-11-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userwarning'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwarning',
            name='viewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
