# Generated by Django 5.2.5 on 2025-11-10 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userwarning_viewed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwarning',
            name='justification',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userwarning',
            name='justification_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
