# Generated by Django 5.2.5 on 2025-11-17 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EcoTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('energy', 'Energy Saving'), ('waste', 'Waste Reduction'), ('transport', 'Green Transport'), ('food', 'Sustainable Eating'), ('home', 'Eco Home'), ('shopping', 'Conscious Shopping')], max_length=50)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Advanced')], max_length=20)),
                ('estimated_impact', models.CharField(help_text="e.g., 'Saves 2kg CO2 per month'", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SustainabilityBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='🏆', max_length=10)),
                ('criteria', models.JSONField(help_text='Requirements to earn this badge')),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], default='common', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='carbon_impact',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='CO2 saved in kg', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='challenge_duration',
            field=models.PositiveIntegerField(blank=True, help_text='Challenge duration in days', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='impact_category',
            field=models.CharField(blank=True, choices=[('energy', 'Energy Saving'), ('waste', 'Waste Reduction'), ('transport', 'Sustainable Transport'), ('food', 'Sustainable Food'), ('water', 'Water Conservation'), ('biodiversity', 'Biodiversity Protection')], max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(blank=True, help_text='Location for local impact', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='participants_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('text', 'Text Post'), ('image', 'Image Post'), ('link', 'Link Share'), ('achievement', 'Achievement'), ('challenge', 'Sustainability Challenge'), ('tip', 'Eco Tip'), ('milestone', 'Project Milestone'), ('impact', 'Environmental Impact')], default='text', max_length=20),
        ),
        migrations.CreateModel(
            name='ImpactTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impact_type', models.CharField(choices=[('carbon_saved', 'Carbon Footprint Reduced'), ('waste_reduced', 'Waste Reduced'), ('energy_saved', 'Energy Saved'), ('water_saved', 'Water Conserved'), ('trees_planted', 'Trees Planted'), ('plastic_avoided', 'Plastic Avoided')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(default='kg', max_length=20)),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='community.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impact_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_recorded'],
            },
        ),
        migrations.CreateModel(
            name='LocalImpactGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_groups', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='local_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChallengeParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('completion_proof', models.ImageField(blank=True, null=True, upload_to='challenge_proofs/')),
                ('impact_achieved', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('challenge_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='community.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'challenge_post')},
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.sustainabilitybadge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
