# Generated by Django 5.2.5 on 2025-11-17 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_ecotip_sustainabilitybadge_post_carbon_impact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengeparticipation',
            name='challenge_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='community.post'),
        ),
    ]
