# Generated by Django 5.2.5 on 2025-11-17 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('user_registered', 'User Registered'), ('user_login', 'User Login'), ('user_logout', 'User Logout'), ('profile_updated', 'Profile Updated'), ('project_created', 'Project Created'), ('project_joined', 'Project Joined'), ('project_left', 'Project Left'), ('project_updated', 'Project Updated'), ('event_created', 'Event Created'), ('event_joined', 'Event Joined'), ('event_left', 'Event Left'), ('topic_created', 'Topic Created'), ('post_created', 'Post Created'), ('comment_created', 'Comment Created'), ('community_post_created', 'Community Post Created'), ('community_comment_created', 'Community Comment Created'), ('user_followed', 'User Followed'), ('user_unfollowed', 'User Unfollowed'), ('resource_created', 'Resource Created'), ('resource_shared', 'Resource Shared'), ('user_warned', 'User Warned'), ('user_banned', 'User Banned'), ('content_moderated', 'Content Moderated')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='activity_lo_user_id_04b3d2_idx'), models.Index(fields=['action_type', '-created_at'], name='activity_lo_action__3c12a3_idx'), models.Index(fields=['-created_at'], name='activity_lo_created_42f1fb_idx')],
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('failed_login', 'Failed Login Attempt'), ('password_changed', 'Password Changed'), ('email_changed', 'Email Changed'), ('suspicious_activity', 'Suspicious Activity'), ('account_locked', 'Account Locked'), ('account_unlocked', 'Account Unlocked'), ('two_factor_enabled', 'Two Factor Authentication Enabled'), ('two_factor_disabled', 'Two Factor Authentication Disabled')], max_length=50)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='security_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='activity_lo_user_id_ee3dd7_idx'), models.Index(fields=['event_type', '-created_at'], name='activity_lo_event_t_84beeb_idx'), models.Index(fields=['ip_address', '-created_at'], name='activity_lo_ip_addr_b23bc3_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('location', models.CharField(blank=True, max_length=200)),
                ('device_type', models.CharField(blank=True, max_length=50)),
                ('browser', models.CharField(blank=True, max_length=100)),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_log', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-login_time'],
                'indexes': [models.Index(fields=['user', '-login_time'], name='activity_lo_user_id_3bb0d8_idx'), models.Index(fields=['session_key'], name='activity_lo_session_5a00b9_idx')],
            },
        ),
    ]
